#!/usr/bin/env python
# coding: utf-8

# # Wave-Particle Duality
# ## 🎲 Particle-like features of light.
# 
# 1. Which of the following phenomena are strongly associated with the particle-like nature of light. 
# 
# A. Blackbody radiation 
# 
# B. Compton Scattering 
# 
# C. Electron Diffraction 
# 
# D. Stern-Gerlach Experiment 
# 
# E. Photoelectric effect
# 
# **Answer**: A, B, C
# 
# -----
# 
# ## 🎲 Properties of photons
# 
# 1. Which of the following changes would double the energy of a photon:
# 
# A. Doubling its frequency 
# 
# B. Doubling its wavelength 
# 
# C. Doubling its momentum 
# 
# D. Doubling its speed 
# 
# E. Doubling its effective (relativistic) mass 
# 
# F. Doubling its wavenumber.
# 
# **Answer**: A
# 
# 
# --------
# 
# 
# 2. A helium-neon laser emits light at 632.8 nm.  What is the energy of the photons generated by this laser, in Joules?
# 
# **Answer**: 123.4
